<?xml version="1.0" encoding="UTF-8"?><testrun name="ServerUnitTests" project="Record_Indexer" tests="11" started="0" failures="0" errors="1" ignored="0">
  <testsuite name="server.ServerUnitTests" incomplete="true">
    <error>server.database.DatabaseException: Error adding User: [SQLITE_CONSTRAINT]  Abort due to constraint violation (column username is not unique)
	at server.access.UserDAO.insertNewUser(UserDAO.java:195)
	at shared.DataImporter.importUser(DataImporter.java:153)
	at shared.DataImporter.importDataToDatabaseWithIndexer(DataImporter.java:93)
	at shared.DataImporter.importData(DataImporter.java:74)
	at server.ServerUnitTests.setUpBeforeClass(ServerUnitTests.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.sql.SQLException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (column username is not unique)
	at org.sqlite.DB.newSQLException(DB.java:383)
	at org.sqlite.DB.newSQLException(DB.java:387)
	at org.sqlite.DB.execute(DB.java:342)
	at org.sqlite.DB.executeUpdate(DB.java:363)
	at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85)
	at server.access.UserDAO.insertNewUser(UserDAO.java:183)
	... 19 more

</error>
    <testcase name="validateUserTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="invalidUserTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="invalidInputUserTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="getProjectsTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="getProjectsInvalidTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="getSampleImageTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="downloadBatchTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="getFieldsFromProjectTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="getAllFieldsTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="submitBatchTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="searchTest" classname="server.ServerUnitTests" incomplete="true"/>
  </testsuite>
</testrun>
