<?xml version="1.0" encoding="UTF-8"?><testrun name="Record_Indexer" project="Record_Indexer" tests="8" started="8" failures="1" errors="0" ignored="0">
  <testsuite name="server.ServerUnitTests" time="0.0">
    <testcase name="test_1" classname="server.ServerUnitTests" time="0.0"/>
  </testsuite>
  <testsuite name="server.access.UserDAOTest" time="1.214">
    <testcase name="testGetAll" classname="server.access.UserDAOTest" time="0.86"/>
    <testcase name="testAdd" classname="server.access.UserDAOTest" time="0.108"/>
    <testcase name="testUpdate" classname="server.access.UserDAOTest" time="0.072"/>
    <testcase name="testDelete" classname="server.access.UserDAOTest" time="0.088"/>
    <testcase name="testInvalidAdd" classname="server.access.UserDAOTest" time="0.043"/>
    <testcase name="testInvalidUpdate" classname="server.access.UserDAOTest" time="0.043">
      <failure>java.lang.AssertionError: Expected exception: server.DatabaseException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</failure>
    </testcase>
  </testsuite>
  <testsuite name="client.ClientUnitTests" time="0.0">
    <testcase name="test_1" classname="client.ClientUnitTests" time="0.0"/>
  </testsuite>
</testrun>
