<?xml version="1.0" encoding="UTF-8"?><testrun name="Rerun server.ServerUnitTests (Failed Tests first)" project="Record_Indexer" tests="7" started="0" failures="0" errors="1" ignored="0">
  <testsuite name="server.ServerUnitTests" incomplete="true">
    <error>server.database.DatabaseException: Could not end transaction
	at server.database.Database.endTransaction(Database.java:89)
	at shared.DataImporter.importDataToDatabaseWithIndexer(DataImporter.java:105)
	at shared.DataImporter.importData(DataImporter.java:74)
	at server.ServerUnitTests.setUpBeforeClass(ServerUnitTests.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.sql.SQLException: database connection closed
	at org.sqlite.Conn.checkOpen(Conn.java:227)
	at org.sqlite.Conn.rollback(Conn.java:348)
	at server.database.Database.endTransaction(Database.java:85)
	... 18 more

</error>
    <testcase name="downloadBatchTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="validateUserTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="invalidUserTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="invalidInputUserTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="getProjectsTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="getProjectsInvalidTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="getSampleImageTest" classname="server.ServerUnitTests" incomplete="true"/>
  </testsuite>
</testrun>
